config/routes.rb
Rails.application.routes.draw do
  get "orders/index"
  resources :product_listing_pages

  root "product_listing_pages#index"

  get "signup", to: "users#new", as: "signup"
  post "signup", to: "users#create"

  get "login", to: "sessions#new", as: "login"
  post "login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, only: [:index, :destroy, :update, :edit] do
    get "purchased_products", to: "users#purchased_products", on: :member
  end

  resources :orders, only: [:index]

  resources :cart_items, only: [:index, :create, :update, :destroy, :show] do
    member do
      patch :increment
      patch :decrement
    end
    collection do
      match :purchase, via: [:get, :post]
      # post :purchase
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/product_listing_page.rb
class ProductListingPage < ApplicationRecord
  has_one_attached :image
  
  has_many :cart_items, dependent: :destroy
  has_many :users, through: :cart_items, dependent: :destroy
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/product_listing_pages_controller.rb
class ProductListingPagesController < ApplicationController
  before_action :set_product_listing_page, only: %i[ destroy show edit update ]
  before_action :authenticate_admin!, only: %i[new create edit update destroy]

  # GET /product_listing_pages
  def index
    @product_listing_pages = ProductListingPage.all

    if current_user.present?
      @cart_items = current_user.cart_items.includes(:product_listing_page).where(order_status: "pending")
    end

    if params[:category].present? && params[:category] != "All"
      @product_listing_pages = @product_listing_pages.where("LOWER(category) = ?", params[:category].downcase)
    end

    if params[:pricerange].present?
      price_range = params[:pricerange].split("-")
      Rails.logger.info "[productController::index] = #{price_range}"
      @product_listing_pages = @product_listing_pages.where("price BETWEEN ? AND ?", price_range[0].to_i, price_range[1].to_i)
    end
  end


  # GET /product_listing_pages/1
  def show
    if current_user.present?
      @cart_items = current_user.cart_items.includes(:product_listing_page).where(order_status: "pending")
    end
    @override_image = true
  end

  # GET /product_listing_pages/neproduct_listing_pagew
  def new
    if current_user.present?
      @cart_items = current_user.cart_items.includes(:product_listing_page).where(order_status: "pending")
    end

    @product_listing_page = ProductListingPage.new
  end

  # GET /product_listing_pages/1/edit
  def edit
  end

  # POST /product_listing_pages
  def create
    @product_listing_page = ProductListingPage.new(product_listing_page_params)

    respond_to do |format|
      if @product_listing_page.save
        format.html { redirect_to product_listing_page_url(@product_listing_page), notice: "Product listing page was successfully created." }
        format.json { render :show, status: :created, location: @product_listing_page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_listing_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_listing_pages/1
  def update
    respond_to do |format|
      if @product_listing_page.update(product_listing_page_params)
        format.html { redirect_to product_listing_page_url(@product_listing_page), notice: "Product listing page was successfully updated." }
        format.json { render :show, status: :ok, location: @product_listing_page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product_listing_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_listing_pages/1
  def destroy
    @product_listing_page.destroy!

    respond_to do |format|
      format.html { redirect_to product_listing_pages_url, notice: "Product listing page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use common setup or constraints between actions.
  def set_product_listing_page
    @product_listing_page = ProductListingPage.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_listing_page_params
    params.require(:product_listing_page).permit(:title, :price, :description, :category, :image, :quantity)
  end

  # def authenticate_admin!
  #   unless current_user&.admin?
  #     redirect_to root_path, alert: "You are not authorized to perform this action."
  #   end
  # end
end

app/helpers/product_listing_pages_helper.rb
module ProductListingPagesHelper
end

app/views/product_listing_pages/_form.html.erb
<%= form_with(model: product_listing_page, id: "productForm") do |form| %>
  <% if product_listing_page.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product_listing_page.errors.count, "error") %> prohibited this product_listing_page from being saved:</h2>
      <ul>
        <% product_listing_page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: 'form-field' %>
    <p class="error title-error" class:'form-error'></p>
  </div>
  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price, class: 'form-field' %>
    <p class="error price-error" class:'form-error'></p>
  </div>
  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class: 'form-field' %>
    <p class="error description-error" class:'form-error'></p>
  </div>
  <div>
    <label for="category" style="display: block" >Category</label>
    <select name="product_listing_page[category]" id="categorySelect" class="form-field">
      <option value="">select category</option>
      <option value="Mobiles">Mobiles</option>
      <option value="Laptops">Laptops</option>
      <option value="Charger">Charger</option>
      <option value="Fashion">Fashion</option>
      <option value="Movies">Movies</option>
    </select>
    <p class="error category-error" class:'form-error'></p>
  </div>
  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity,class:'form-field'  %>
    <p class="error quantity-error" class:'form-error'></p>
  </div>
  <div>
    <%= form.label :image, 'Upload Image', style: 'display: block' %>
    <%= form.file_field :image, class: 'form-field' %>
    <p class="error image-error" class:'form-error'></p>
  </div>
  <div class="bottom-button">
    <%= link_to "Back", product_listing_pages_path %>
    <%= form.submit "Add", class: 'btn' %>
  </div>
<% end %>

<%= javascript_include_tag 'formvalidate' %>

app/views/product_listing_pages/_popover.html.erb
<%= form_tag(product_listing_pages_path, method: :get, class:'filters-form') do %>
  <%= select_tag :category, options_for_select(['All', 'Mobiles', 'Laptops', 'Charger', 'Fashion', 'Movies'], params[:category]), prompt: 'Select Category',class:'popover-form' %>
  <%= select_tag :pricerange, options_for_select(['49- 499', '500-999', '1000-1999', '2000-2999', '3000-10000'], params[:pricerange]), prompt: 'Price Range',class:'popover-form' %>
</select>
<button type="submit" class="submit" data-close-button >Apply</button>
<% end %>

app/views/product_listing_pages/_product_listing_page.html.erb
<div id="<%= dom_id product_listing_page %>" class='<%= 'product-list ' if @override_image.present? %>'>
  <div class="image <%= 'image-override' if @override_image.present? %>">
    <%=image_tag product_listing_page.image %>
  </div>
  <div class='detail <%= 'details' if @override_image.present? %>'>
    <%if !@override_image.present?%>
      <h2>
        <%= product_listing_page.title %>
      </h2>
    <%else%>
      <p>
        <strong>Title : </strong>
        <%= product_listing_page.title %>
      </p>
    <%end%>
    <%if !@override_image.present?%>
      <h3>
        <%= number_to_currency(product_listing_page.price) %>
      </h3>
    <%else%>
      <p>
        <strong>Price : </strong>
        <%= number_to_currency(product_listing_page.price) %>
      <%end%>
      <p>
        <% if @override_image.present? %>
          <strong>Description:</strong>
          <%= product_listing_page.description %>
        <% end %>
      </p>
      <p>
        <strong>Quantity:</strong>
        <%= product_listing_page.quantity %>
      </p>
      <p>
        <strong>Category:</strong>
        <%= product_listing_page.category %>
      </p>
    </div>
  </div>

app/views/product_listing_pages/edit.html.erb
<div class="form-page">
  <div class='new_form'>
    <h3>Edit product</h3>
      <%= render "form", product_listing_page: @product_listing_page %>
    <br>
  </div>
</div>

app/views/product_listing_pages/index.html.erb
<div class='search'>
  <input type="text" placeholder="Search" class='search-input' id="search-product">
  <div>
    <button data-modal-target="#modal" class="filter-button" title="filter by category or price range">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" id="filter" style="width: 16px; height: 16px; margin: 2px;">
        <path d="M2 7h.142a3.981 3.981 0 0 0 7.716 0H30a1 1 0 0 0 0-2H9.858a3.981 3.981 0 0 0-7.716 0H2a1 1 0 0 0 0 2zm4-3a2 2 0 1 1-2 2 2 2 0 0 1 2-2zm24 11h-.142a3.981 3.981 0 0 0-7.716 0H2a1 1 0 0 0 0 2h20.142a3.981 3.981 0 0 0 7.716 0H30a1 1 0 0 0 0-2zm-4 3a2 2 0 1 1 2-2 2 2 0 0 1-2 2zm4 7H19.858a3.981 3.981 0 0 0-7.716 0H2a1 1 0 0 0 0 2h10.142a3.981 3.981 0 0 0 7.716 0H30a1 1 0 0 0 0-2zm-14 3a2 2 0 1 1 2-2 2 2 0 0 1-2 2z"></path>
      </svg>
    </button>
    <div class="modal" id="modal">
      <div class="modal-header">
        <div class="title">Filter</div>
        <button data-close-button class="close-button">&times;</button>
      </div>
      <div class="modal-body">
        <%= render "popover"%>
      </div>
    </div>
    <div id="overlay"></div>
  </div>
</div>
<div class="product" >
  <% @product_listing_pages.each do |product_listing_page| %>
    <a href="<%= product_listing_page_path(product_listing_page) %>" class="anchor-tag">
      <div class ="product-details">
        <div class="details-list">
          <%= render product_listing_page %>
        </div>
        <%= button_to  product_listing_page.quantity < 1 ? 'Out of Stock' : 'Buy Now', 
        cart_items_path(product_listing_page_id: product_listing_page.id ), method: :post, 
        remote: true, class: product_listing_page.quantity < 1 ? "out-of-stock" : "buy-now" ,onclick: 'event.stopPropagation()',data:{turbo:true}   ,  
        disabled: product_listing_page.quantity < 1   %>
      </div>
    </a>
  <% end %>
</div>
<%= javascript_include_tag 'popover' %>
<%= javascript_include_tag 'search' %>

app/views/product_listing_pages/new.html.erb
<div class="form_page">
  <div class='new_form'>
    <h3>New product</h3>
    <%= render "form", product_listing_page: @product_listing_page %>
  </div>
</div>

app/views/product_listing_pages/show.html.erb
<div class='product-details'>
  <div class="product-more">
    <%= render @product_listing_page %>
  </div>
  <div class='links'>
    <%= link_to "Back", product_listing_pages_path ,class:"detail-links" %>
    <% if current_user&.admin?  %>
      <%= link_to "Update", edit_product_listing_page_path(@product_listing_page) ,class:"detail-links" %>
      <%= button_to "Delete", @product_listing_page, method: :delete ,class:"detail-links"%>
    <% end %>
    <%= button_to 'Buy Now', cart_items_path(product_listing_page_id: @product_listing_page.id), method: :post, remote: true, onclick: 'event.stopPropagation()',data:{turbo:false},class:"detail-links"  %>
  </div>
</div>