config/routes.rb
Rails.application.routes.draw do
  get "orders/index"
  resources :product_listing_pages

  root "product_listing_pages#index"

  get "signup", to: "users#new", as: "signup"
  post "signup", to: "users#create"

  get "login", to: "sessions#new", as: "login"
  post "login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, only: [:index, :destroy, :update, :edit] do
    get "purchased_products", to: "users#purchased_products", on: :member
  end

  resources :orders, only: [:index]

  resources :cart_items, only: [:index, :create, :update, :destroy, :show] do
    member do
      patch :increment
      patch :decrement
    end
    collection do
      match :purchase, via: [:get, :post]
      # post :purchase
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :name, presence: true
    validates :email, presence: true, uniqueness: true

    has_many :cart_items ,dependent: :destroy 
    has_many :product_listing_pages, through: :cart_items,dependent: :destroy
end
        

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_admin!, only: %i[index edit update destroy]

  def index
    if current_user.present?
      @cart_items = current_user.cart_items.includes(:product_listing_page).where(order_status: "pending")
    end
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    puts "akgami #{current_user&.admin}"
    if current_user&.admin?
      if @user.save
        redirect_to users_path, notice: "User #{@user.name} created successfully."
      else
        render :new
      end
    elsif @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path, notice: "User updated successfully."
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy!
    redirect_to users_path, notice: "User deleted successfully."
  end

  def purchased_products
    @user = User.find(params[:id])
    @purchased_products = @user.cart_items.purchased
    puts "god mode $ #{@purchased_products}"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :phone_number, :address)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="form_page">
  <div class='edit_form'>
    <h3 class="edit-user">Edit User</h3>
    <%= form_with(model: @user, url: user_path(@user), method: :patch) do |form| %>
      <div class="edit_user">
        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, required: true %>
        </div>
        <div class="form-group">
          <%= form.label :email %>
          <%= form.email_field :email, required: true %>
        </div>
        <div class="form-group">
          <%= form.label :password %>
          <%= form.password_field :password %>
        </div>
        <div class="form-group">
          <%= form.label :password_confirmation %>
          <%= form.password_field :password_confirmation %>
        </div>
        <div class="form-group">
          <%= form.label :phone_number %>
          <%= form.text_field :phone_number, required: true %>
        </div>
        <div class="form-group">
          <%= form.label :address %>
          <%= form.text_field :address, required: true %>
        </div>
        <div class="form-group">
          <%= form.submit "Update User", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users Management</h1>
<div class="actions">
  <%= link_to 'New User', signup_path, class: 'btn-new' %>
</div>
<div class="users-list">
  <% @users.each do |user| %>
    <div class="user-card">
      <div class="user-details">
        <div class="user-detail"><strong>Name:</strong> <%= user.name %></div>
        <div class="user-detail"><strong>Email:</strong> <%= user.email %></div>
        <div class="user-detail"><strong>Phone Number:</strong> <%= user.phone_number %></div>
        <div class="user-detail"><strong>Address:</strong> <%= user.address %></div>
      </div>
      <div class="user-actions">
        <%= link_to 'Edit', edit_user_path(user), class: 'btn btn-edit' %>
        <%= button_to 'Delete', user_path(user), method: :delete, class: 'btn btn-delete' %>
        <%= link_to 'View Purchased Products', purchased_products_user_path(user), class: 'btn btn-view-products' %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="form_page">
  <div class='new_form'>
    <h3>Sign Up</h3>
    <%= form_with(model: @user, url: signup_path, id: "signup-form" ) do |form| %>
      <div class="signup">
        <div>
          <%= form.label :name, style: "display: block" %>
          <%= form.text_field :name %>
          <p id="name-error" class="error-message">Name is required.</p>
        </div>
        <div>
          <%= form.label :email, style: "display: block" %>
          <%= form.email_field :email %>
          <p id="email-error" class="error-message">A valid email is required.</p>
        <div>
          <%= form.label :password, style: "display: block" %>
          <%= form.password_field :password %>
          <p id="password-error" class="error-message">Password must be at least 6 characters long.</p>
        </div>
        <div>
          <%= form.label :password_confirmation, style: "display: block" %>
          <%= form.password_field :password_confirmation %>
          <p id="password_confirmation-error" class="error-message">Passwords do not match.</p>
        </div>
        <div>
          <%= form.label :phone_number, style: "display: block" %>
          <%= form.text_field :phone_number %>
          <p id="phone_number-error" class="error-message">Phone number is required.</p>
        </div>
        <div>
          <%= form.label :address, style: "display: block" %>
          <%= form.text_field :address %>
          <p id="address-error" class="error-message">Address is required.</p>
        </div>
        <div>
          <%= form.submit "Sign Up" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= javascript_include_tag 'signUpvalidation' %>

app/views/users/purchased_products.html.erb
<h1>Purchased Products by <%= @user.name %></h1>
<div class="orders">
  <% @purchased_products.each do |order| %>
    <div class="order"> 
      <h3>Order Date: <%= order.updated_at.strftime("%B %d, %Y %I:%M %p") %></h3>
      <div class="order-details">
        <p>Product: <%= order.product_listing_page.title %></p>
        <p>Quantity: <%= order.quantity %></p>
        <p>Total Price: <%= number_to_currency(order.product_listing_page.price * order.quantity) %></p>
      </div>
    </div>
  <% end %>
</div>