config/routes.rb
Rails.application.routes.draw do
  get "orders/index"
  resources :product_listing_pages

  root "product_listing_pages#index"

  get "signup", to: "users#new", as: "signup"
  post "signup", to: "users#create"

  get "login", to: "sessions#new", as: "login"
  post "login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, only: [:index, :destroy, :update, :edit] do
    get "purchased_products", to: "users#purchased_products", on: :member
  end

  resources :orders, only: [:index]

  resources :cart_items, only: [:index, :create, :update, :destroy, :show] do
    member do
      patch :increment
      patch :decrement
    end
    collection do
      match :purchase, via: [:get, :post]
      # post :purchase
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<div class="header">
  <div class='header-left'>
    <div class='logo-header'>
      <a href='/product_listing_pages' data: { turbo: true } >
        <%= image_tag "logo.png", alt: "Market" ,class:"logo"%>
      </a>
    </div>
    <% if current_user&.admin?  %>
      <div>
        <a href='/product_listing_pages/new' class"nav-link" >
          <svg xmlns="http://www.w3.org/2000/svg" height="20" viewBox="0 0 512 512">
            <!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M512 416c0 35.3-28.7 64-64 64H64c-35.3 0-64-28.7-64-64V96C0 60.7 28.7 32 64 32H192c20.1 0 39.1 9.5 51.2 25.6l19.2 25.6c6 8.1 15.5 12.8 25.6 12.8H448c35.3 0 64 28.7 64 64V416zM232 376c0 13.3 10.7 24 24 24s24-10.7 24-24V312h64c13.3 0 24-10.7 24-24s-10.7-24-24-24H280V200c0-13.3-10.7-24-24-24s-24 10.7-24 24v64H168c-13.3 0-24 10.7-24 24s10.7 24 24 24h64v64z"/></svg>
        </a>
      </div>
      <div>
        <a href='/users' class"nav-link" >
          <svg xmlns="http://www.w3.org/2000/svg" height="20" viewBox="0 0 640 512"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M144 0a80 80 0 1 1 0 160A80 80 0 1 1 144 0zM512 0a80 80 0 1 1 0 160A80 80 0 1 1 512 0zM0 298.7C0 239.8 47.8 192 106.7 192h42.7c15.9 0 31 3.5 44.6 9.7c-1.3 7.2-1.9 14.7-1.9 22.3c0 38.2 16.8 72.5 43.3 96c-.2 0-.4 0-.7 0H21.3C9.6 320 0 310.4 0 298.7zM405.3 320c-.2 0-.4 0-.7 0c26.6-23.5 43.3-57.8 43.3-96c0-7.6-.7-15-1.9-22.3c13.6-6.3 28.7-9.7 44.6-9.7h42.7C592.2 192 640 239.8 640 298.7c0 11.8-9.6 21.3-21.3 21.3H405.3zM224 224a96 96 0 1 1 192 0 96 96 0 1 1 -192 0zM128 485.3C128 411.7 187.7 352 261.3 352H378.7C452.3 352 512 411.7 512 485.3c0 14.7-11.9 26.7-26.7 26.7H154.7c-14.7 0-26.7-11.9-26.7-26.7z"/></svg>
        </a>
      </div>
    <%end%>
    <div>
      <%= link_to "My Orders", orders_path %>
    </div>
  </div>
  <div class='header-right'>
    <% if logged_in? %>
      <div>
        <%= link_to cart_items_path, class: "nav-link", data: { turbo: false } do %>
          <i style="font-size:25px" class="fa">&#xf07a; 
            <span class='header-cart-Items'>
              <% if @cart_items&.length %>
                <%= @cart_items.length %>
              <% end %>
            </span>
          </i>
        <% end %>
      </div>
      <div>
        <%= button_to 'Log Out', logout_path, method: :delete, class:'log-out'%>
      </div>
    <% else %>
      <div>
        <%= link_to 'Sign Up', signup_path ,data: { turbo: false }%> | <%= link_to 'Log In', login_path ,data: { turbo: false }%>
      </div>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<h1>Welcome to the App</h1>