config/routes.rb
Rails.application.routes.draw do
  get "orders/index"
  resources :product_listing_pages

  root "product_listing_pages#index"

  get "signup", to: "users#new", as: "signup"
  post "signup", to: "users#create"

  get "login", to: "sessions#new", as: "login"
  post "login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, only: [:index, :destroy, :update, :edit] do
    get "purchased_products", to: "users#purchased_products", on: :member
  end

  resources :orders, only: [:index]

  resources :cart_items, only: [:index, :create, :update, :destroy, :show] do
    member do
      patch :increment
      patch :decrement
    end
    collection do
      match :purchase, via: [:get, :post]
      # post :purchase
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :product_listing_page
  validates :quantity, presence: true, numericality: { greater_than: 0 }
  
  scope :purchased, -> { where(order_status: "completed").order(updated_at: :desc) }
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :require_login

  def index
    @cart_items = current_user.cart_items.includes(:product_listing_page).where(order_status: "pending")
    @total_price = @cart_items.sum { |cart_item| cart_item.product_listing_page.price }
  end

  def create
    product = ProductListingPage.find(params[:product_listing_page_id])
    cart_item = current_user.cart_items.find_or_initialize_by(product_listing_page: product, order_status: "pending")
    if cart_item.new_record?
      cart_item.save
      redirect_to product_listing_pages_path, notice: "Product added to cart."
    elsif product.quantity > cart_item.quantity
      cart_item.quantity += 1
      cart_item.save
      redirect_to product_listing_pages_path, notice: "Product quantity updated in cart."
    else
      redirect_to product_listing_pages_path, alert: "Product out of stock."
    end
  end

  def increment
    current_cart_item = current_user.cart_items.find(params[:id])
    product = current_cart_item.product_listing_page

    if product.quantity > current_cart_item.quantity
      current_cart_item.increment!(:quantity)
      flash[:notice] = "Product quantity updated."
    else
      flash[:alert] = "Product quantity exceeds available stock."
    end

    redirect_to cart_items_path
  end

  def decrement
    cart_item = current_user.cart_items.find(params[:id])
    if cart_item.quantity > 1
      cart_item.decrement!(:quantity)
      redirect_to cart_items_path, notice: "Product decremented updated."
    else
      redirect_to cart_items_path, notice: "you should click remove "
    end
  end

  def destroy
    cart_item = current_user.cart_items.find(params[:id])
    cart_item.destroy
    redirect_to cart_items_path, notice: "Product removed from cart."
  end

  # def purchase
  #   @cart_items = current_user.cart_items.includes(:product_listing_page).where(order_status: "pending")

  #   @cart_items.each do |cart_item|
  #     product = cart_item.product_listing_page

  #     if product.quantity >= cart_item.quantity
  #       product.update(quantity: product.quantity - cart_item.quantity)
  #       cart_item.update(order_status: "completed", updated_at: Time.current) # Use updated_at as purchase date
  #     else
  #       flash[:alert] = "Not enough stock for #{product.title}. Purchase aborted."
  #       redirect_to cart_items_path and return
  #     end
  #   end

  #   flash[:notice] = "Purchase completed successfully."
  #   redirect_to cart_items_path
  # end

  def purchase
    @cart_items = current_user.cart_items.includes(:product_listing_page).where(order_status: "pending")

    if request.post?
      @cart_items.each do |cart_item|
        product = cart_item.product_listing_page

        if product.quantity >= cart_item.quantity
          product.update(quantity: product.quantity - cart_item.quantity)
          cart_item.update(order_status: "completed", updated_at: Time.current) # Use updated_at as purchase date
        else
          flash[:alert] = "Not enough stock for #{product.title}. Purchase aborted."
          redirect_to cart_items_path and return
        end
      end

      current_user.update(address: params[:address], phone_number: params[:phone_number])

      flash[:notice] = "Purchase completed successfully."
      redirect_to cart_items_path
    else
      # Render the form for address and phone number
    end
  end

  private

  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to login_path
    end
  end

  def cart_item_params
    params.require(:cart_item).permit(:quantity)
  end
end

app/views/cart_items/index.html.erb
<h2 class="cart-head">Your Cart</h2>
<div class="cart-page">
  <div class="cart-page-left">
    <%if @cart_items.length > 0 %>
      <% @cart_items.each do |cart_item| %>
        <div class="cart">
          <div class="cart-image">
            <%= image_tag cart_item.product_listing_page.image if cart_item.product_listing_page.image.present?  %>
          </div>
          <div class="cart-details">
            <div class="cart-title-price">
              <div>
                <h3><%= cart_item.product_listing_page.title %></h3>
              </div>
              <h4 class='price'>
                <%= number_to_currency(cart_item.product_listing_page.price) %>
              </h4>
            </div>
            <p class="cart-description two-lines">
              <%= cart_item.product_listing_page.description %>
            </p>
            <div class="cart-quantity-delete">
              <div class="cart-quantity">
                <%= button_to ' - ', decrement_cart_item_path(cart_item), method: :patch, class: 'quantity-btn' %>
                <span>&nbsp; Quantity: <%= cart_item.quantity %>&nbsp;</span>
                <%= button_to ' + ', increment_cart_item_path(cart_item), method: :patch, class: 'quantity-btn' %>
              </div>
              <%= button_to 'Remove', cart_item_path(cart_item), method: :delete ,class:'delete-btn' %>
            </div>
          </div>
        </div>
      <% end %>
    <%else%>
      <div class="empty-message">
        <h3 >Your cart is empty.</h3>
        <div>
          <a href='/product_listing_pages' data: { turbo: true } class="anchor" >
            Go to Market
          </a>
        </div>
      </div>
    <% end %>
  </div>
  <div class="cart-page-right">
    <h2 class="h">Price Details</h2>
    <hr>
    <% total_price = @cart_items.sum { |cart_item| cart_item.product_listing_page.price * cart_item.quantity } %>
    <div class="price-details">
      <h3>Items </h3>
      <p><%= @cart_items.sum{|ele| ele.quantity}%> </p>
    </div>
    <div class="price-details">
      <h3>Total Price:</h3>
      <p><%= number_to_currency(total_price) %> </p>
    </div>
  </div>
</div>

<div class="cart-head cart-bottom">
  <%= link_to 'back', product_listing_pages_path ,class:"na-link back-btn" %>
  <% if @cart_items.length > 0 %>
    <%= link_to 'PLACE ORDER', purchase_cart_items_path, class: "place-order" %>
  <% end %>
</div>

app/views/cart_items/purchase.html.erb
<h2 class="cart-head">Delivery Information</h2>
<div class="delivery-form">
  <%= form_with(url: purchase_cart_items_path, method: :post, class: "form") do %>
    <div class="form-group">
      <%= label_tag :address, "Delivery Address", class: "form-label" %>
      <%= text_field_tag :address, current_user.address, required: true, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= label_tag :phone_number, "Phone Number", class: "form-label" %>
      <%= text_field_tag :phone_number, current_user.phone_number, required: true, class: "form-control" %>
    </div>
    <div>
      <%=link_to "back",cart_items_path, class: "nav-link", data: { turbo: false } %>
      <%= submit_tag "Confirm and Place Order", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>